// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIGexOT1HcM4doyFBjw-LVMdWLmLYlaNQ',
    appId: '1:155223789652:android:015105783e06131e10ddc1',
    messagingSenderId: '155223789652',
    projectId: 'yusr-applicatin',
    storageBucket: 'yusr-applicatin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1RhBLY8aO_3PqmIwsasc0HYMEFD9RNk',
    appId: '1:155223789652:ios:fc3d5173372f0c4710ddc1',
    messagingSenderId: '155223789652',
    projectId: 'yusr-applicatin',
    storageBucket: 'yusr-applicatin.firebasestorage.app',
    iosBundleId: 'com.example.yusr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1RhBLY8aO_3PqmIwsasc0HYMEFD9RNk',
    appId: '1:155223789652:ios:fc3d5173372f0c4710ddc1',
    messagingSenderId: '155223789652',
    projectId: 'yusr-applicatin',
    storageBucket: 'yusr-applicatin.firebasestorage.app',
    iosBundleId: 'com.example.yusr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApTlcgLZn3ePqAuZ0yWQGPU3ja0VqzZIk',
    appId: '1:155223789652:web:bada72b7a7eca66d10ddc1',
    messagingSenderId: '155223789652',
    projectId: 'yusr-applicatin',
    authDomain: 'yusr-applicatin.firebaseapp.com',
    storageBucket: 'yusr-applicatin.firebasestorage.app',
    measurementId: 'G-SDNESJBTD0',
  );
}
